language: ruby

rvm:
  - "2.1.0"
  - "2.0.0"
  - "1.9.3"
  - jruby-19mode

gemfile:
  - ".gemfiles/Gemfile.rails-3.2.x"
  - ".gemfiles/Gemfile.rails-4.0.x"
  - ".gemfiles/Gemfile.rails-4.1.x"

matrix:
  include:
    - rvm: "1.8.7"
      gemfile: ".gemfiles/Gemfile.rails-3.2.x"
    - rvm: jruby-18mode
      gemfile: ".gemfiles/Gemfile.rails-3.2.x"
